name: Tests




on:
  pull_request:
    branches:
      - dev
      - release/*




jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ./SubscriptionManager.sln

      - name: Run Unit Tests
        run: dotnet test ./SubscriptionManager.Tests/SubscriptionManager.Tests.csproj --configuration Release
